import { PenIcon, EraserIcon, HighlighterIcon, TextIcon } from './icons/ToolIcons';

export const TOOLS = [
  {
    tool: "pen",
    icon: PenIcon,
    title: "Pen",
  },
  {
    tool: "eraser",
    icon: EraserIcon,
    title: "Eraser",
  },
  {
    tool: "highlighter",
    icon: HighlighterIcon,
    title: "Highlighter",
  },
  {
    tool: "text",
    icon: TextIcon,
    title: "Text",
  },
  // { tool: "rectangle", icon: "◻️", title: "Rectangle" },
  // { tool: "circle", icon: "⭕", title: "Circle" },
  // { tool: "arrow", icon: "➡️", title: "Arrow" },
];

export const COLORS = [
  "#EF4444",
  "#F97316",
  "#F59E0B",
  "#84CC16",
  "#10B981",
  "#06B6D4",
  "#3B82F6",
  "#6366F1",
  "#8B5CF6",
  "#EC4899",
  "#000000",
  "#FFFFFF",
];

export const STATIC_CONTENT = [

  {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit textDouble click to edit textDouble click to edit textDouble click to edit textDouble click to edit textDouble click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  },  {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  },  {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  },  {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  },
  {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  }, {
    type: "text",
    x: 20,
    y: 50,
    text: "Double click to edit text",
    fontSize: 16,
    fill: "#7f8c8d",
  },
  {
    type: "text",
    x: 20,
    y: 80,
    text: "Use toolbar for more options",
    fontSize: 16,
    fill: "#7f8c8d",
  },
  {
    type: "text",
    x: 20,
    y: 80,
    text: "Use toolbar for more options",
    fontSize: 16,
    fill: "#7f8c8d",
  },
  {
    type: "text",
    x: 20,
    y: 80,
    text: "Use toolbar for more options",
    fontSize: 16,
    fill: "#7f8c8d",
  },
  {
    type: "text",
    x: 20,
    y: 80,
    text: "Use toolbar for more options",
    fontSize: 16,
    fill: "#7f8c8d",
  },
  {
    type: "text",
    x: 20,
    y: 80,
    text: "Use toolbar for more options",
    fontSize: 16,
    fill: "#7f8c8d",
  },
];

export const EXPORT_OPTIONS = [
  { label: "PNG (Standard)", value: "low", icon: "🖼️" },
  { label: "PNG (High Quality)", value: "medium", icon: "🖼️" },
  { label: "PNG (Ultra Quality)", value: "high", icon: "🖼️" },
  { label: "PDF", value: "pdf", icon: "📄" },
];
